dev/jobs/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from .views import (
    home,
    about,
    dev,
    JobsView,
    JobDetailView

)
from . import views

app_name = 'jobs'
urlpatterns = [
   path('home', views.home, name='home'),
   path('about', views.about, name='about'),
   path('', views.dev, name='dev'),
   path('jobs', JobsView.as_view(), name='list'),
   path('jobs/<int:pk>/', JobDetailView.as_view(), name='details'),
    # path('login/', auth_views.LoginView.as_view(template_name='report/login.html'), name='login'),
    # path('logout/', auth_views.LogoutView.as_view(template_name='report/logout.html'), name='logout'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dev/src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("__reload__/", include("django_browser_reload.urls")),
    path('Jobsplus/', include('jobs.urls')),
    path("securedJobs+adminportal/", admin.site.urls),
    # path('profile/', user_views.profile, name='profile'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dev/jobs/models.py
from django.db import models
from django.urls import reverse


class EntrylvlManager(models.Manager):
    # manger for filtering for entry level jobs
    def get_queryset(self):
        return super().get_queryset().filter(job_title="entry level")


class Job(models.Model):
    employer_name = models.CharField(max_length=400, blank=True, null=True)
    employer_logo = models.URLField(max_length=400, blank=True, null=True)
    employer_website = models.URLField(max_length=400, blank=True, null=True)
    employer_company_type = models.CharField(max_length=400, blank=True, null=True)
    job_publisher = models.CharField(max_length=400, blank=True, null=True)
    job_id = models.CharField(max_length=400, blank=True, null=True)
    job_employment_type = models.CharField(max_length=400, blank=True, null=True)
    job_title = models.CharField(max_length=400, blank=True, null=True)
    job_apply_link = models.URLField(max_length=400, blank=True, null=True)
    apply_options = models.JSONField(max_length=400, blank=True, null=True)
    job_apply_is_direct = models.BooleanField(blank=True, null=True)
    job_description = models.TextField(blank=True, null=True)
    job_is_remote = models.BooleanField(blank=True, null=True)
    job_posted_at_datetime_utc = models.DateTimeField(max_length=30, blank=True, null=True)
    job_city = models.CharField(max_length=400, blank=True, null=True)
    job_state = models.CharField(max_length=400, blank=True, null=True)
    job_country = models.CharField(max_length=400, blank=True, null=True)
    job_benefits = models.CharField(max_length=4000, blank=True, null=True)
    job_google_link = models.URLField(max_length=400, blank=True, null=True)
    job_offer_expiration_datetime_utc = models.DateTimeField(
        max_length=30, blank=True, null=True
    )
    job_required_skills = models.TextField(max_length=2000, blank=True, null=True)
    job_experience_in_place_of_education = models.BooleanField(blank=True, null=True)
    job_min_salary = models.FloatField(null=True, max_length=30, blank=True, )
    job_max_salary = models.FloatField(null=True, max_length=30, blank=True )
    job_salary_currency = models.CharField(max_length=200, blank=True, null=True)
    job_salary_period = models.CharField(max_length=200, blank=True, null=True)
    
    job_posting_language = models.CharField(max_length=5, blank=True, null=True)
    job_required_experience = models.JSONField(null=True, blank=True)
    job_required_education = models.JSONField(null=True, blank=True)
    job_highlights = models.JSONField(null=True, blank=True)

    def __str__(self):
        return "{} /by {}/is remote? {}/posted {}".format(
            self.job_title,
            self.employer_name,
            self.job_is_remote,
            self.job_posted_at_datetime_utc,
        )

    def get_absolute_url(self):
        return reverse('details', args=[str(self.pk)])
    
    objects = models.Manager()
    entrylevel = EntrylvlManager()

""""""

dev/jobs/views.py
from django.views.generic import TemplateView, ListView, DetailView
from django_filters.views import FilterView
from django.shortcuts import render, redirect
from jobs.models import Job
from jobs.filters import JobFilter


def home(request):
    return render(request, 'jobs/home.html')

def about(request):
    return render(request, 'jobs/about.html')

def dev(request):
    jobs = Job.objects.all()

    context = {'jobs': jobs}
    return render(request, 'jobs/dev.html', context)

class JobsView(ListView, FilterView):
    model = Job
    template_name = 'jobs/details.html'
    context_object_name = 'jobs'
    filterset_class = JobFilter
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = self.filterset_class(self.request.GET, queryset=queryset)
        return self.filterset.qs

class JobDetailView(DetailView):
    """Detail view that also acts as a list view for searching"""
    model = Job
    template_name = 'jobs/details.html'  

    paginate_by = 5  

    def get_queryset(self):
       
        return Job.objects.all()

    def get_context_data(self, **kwargs):
        """function that list data to be displayed and displays job details when the user selects one"""
        context = super().get_context_data(**kwargs)
        
        job_filter = JobFilter(self.request.GET, queryset=Job.objects.all())
        filtered_jobs = job_filter.qs

        context['jobs'] = filtered_jobs
        context['job_filter'] = job_filter
        return context

dev/src/templates/jobs/about.html
{% extends "jobs/index.html" %}
{% block content %}
<section class="p-5" id="hero">
    <!-- flex container -->
    <div class="container flex flex-col-reverse items-center px-6 mx-auto mt-10 space-y-0 md:flex-row md:space-y-0">
      <!-- left side -->
      <div class="flex flex-col mb-32 space-y-12 md:w-1/2">
        <h1 class="max-w-md mt-2 text-6xl font-bold text-center md:text-5xl md:text-left">
          About Us
        </h1>
        <p class="max-w-sm text-center text-black md:text-left">
          Hi I'm Leslie a self-taught computer programmer from Jamaica who's on the hunt for his first paid tech role,
          this site was made for my portfolio and I've decided to self host it so that I can help out my fellow devs especially in these hard time.
          This site is currently in an early stage so it's very rough but I'm currently planning to do a major update to the site 
          so please understand if it's not the best looking right now.  
        </p>
        <div class="justify-center hidden md:justify-start">
          <a class="p-3 px-6 text-white bg-green-400 rounded-full baseline hover:bg-yellow-500 hover:text-green-500" href="{% url 'jobs:list' %}">Contact me</a>
        </div>
      </div>
      <!-- image -->
      <div class="md:w-1/2">
        <img
          src="https://images.unsplash.com/photo-1599658880436-c61792e70672?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80"
          alt="graphic-3" class="rounded graphic" />
      </div>
    </div>
  </section>

  

{% endblock content %}

dev/src/templates/jobs/details.html
{% extends "jobs/index.html" %}
{% block content %}
<!-- Content goes here 

-->
    
    <div class="flex flex-row justify-center flex-grow w-screen h-screen pt-4 mt-5 mb-12">
  
        <!-- ad -->
        <div class="flex-shrink-0 hidden w-1/6 h-screen p-4 mt-4 border-r-2 ">
            Left menu
        </div>
        <div class="w-5/6 h-screen ">
          
            <div class="flex flex-row justify-center flex-grow pt-4 m-0 ">
              <div class="items-center w-2/5">
                <div class="">    <!-- Links Section -->
                  <div class="items-center hidden space-x-8 lg:flex">
                      <div class="flex text-gray-600 transition-colors duration-300 cursor-pointer  hover:shadow-lg hover:shadow-yellow-500 hover:border-yellow-500 focus:opacity-[0.85] focus:shadow-none active:opacity-[0.85] active:shadow-none disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none">
                          <form class="flex space-x-4">
                              <!-- Form items go here -->
                              <div class="relative flex p-2 bg-white border-2 shadow rounded-xl">
                                  <span class="flex items-center justify-end w-auto p-2 text-gray-500">
                                      <svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path>
                                      </svg>
                                  </span>
                                  <input type="text" id="job_title" name="job_title" class="w-full p-2 text-sm border-0" placeholder="Search Jobs"/>
                              
                              
                                  <div class="flex items-center w-auto mr-2 text-sm text-gray-500 justify-items-center">
                                      <label class="p-1 mt-2" for="job_country">Location: </label>
                                      <input type="text" id="job_country" name="job_country" class="w-full p-0 text-sm border-0" placeholder="Where?"/>
                                  </div>
                              
                                  <div class="flex-1">
                                      <!-- Add more form fields as needed -->
                                  </div>
                              
                                  <div class="flex-1">
                                      <button type="submit" class="flex p-2 text-xl text-green-500 bg-black hover:bg-gray-700 rounded-xl">
                                          <p class="text-sm font-semibold">Search</p>
                                          </button>
                                  </div>
                              </div>
                          </form>
                      </div>
                      
                  </div>
                </div>
                <!-- posts -->
                  <div class="items-center w-full max-h-screen mb-5 mr-5 overflow-y-auto md:flex md:flex-col md-flex-1">
                    {% for job in jobs %}
                      <div class="items-center justify-center w-full max-h-screen">
                          <!-- posts -->
                          <div class="max-w-md p-2 mx-2 mb-4 shadow-md md:p-4 md:mx-6 hover:border-4 hover:border-amber-400">
                              <h2 class="text-xl font-semibold md:text-2xl"><a class="text-green-500 hover:text-black" href="{% url 'jobs:details' pk=job.id%}">{{job.job_title}}</a></h2>
                              <p class="text-sm leading-tight text-justify text-gray-800 truncate md:text-base">{{job.job_description}}</p>
                              <div class="flex justify-between mt-2">
                              <span>Posted On: {{job.job_posted_at_datetime_utc}}</span>
                              <span class="text-black">Date: <a class="text-green-500 hover:text-black" href="#">{{job.apply_options}}</a></span>
                              </div>
                          </div>
                      </div>
                    {% endfor %}
                  </div>
              </div>  
              <div class="w-3/5 ml-5">
                <!-- post view -->
                <div class="right-0 flex-shrink-0 max-h-screen overflow-y-auto">
                  {% include "jobs/partials/info.html" %}
                </div>
              </div>
            </div>
          </div>
          
    </div>
             
    
{% endblock content %}  

dev/src/templates/jobs/dev.html
{% extends "jobs/index.html" %}
{% block content %}
<!-- Content goes here -->
<div class="flex flex-row justify-center flex-grow w-screen h-screen pt-4 mt-5 mb-12">
  
  <!-- ad -->
  <div class="flex-shrink-0 hidden w-1/6 h-screen p-4 mt-4 border-r-2 ">
      Left menu
  </div>
  <div class="w-5/6 h-screen p-0 m-0">
    
      <div class="flex flex-row justify-center flex-grow pt-4 m-0 ">
        <div class="items-center w-2/5">
          <div class="">    <!-- Links Section -->
            <div class="items-center hidden space-x-8 lg:flex">
                <div class="flex text-gray-600 transition-colors duration-300 cursor-pointer mb-5 hover:shadow-lg hover:shadow-yellow-500 hover:border-yellow-500 focus:opacity-[0.85] focus:shadow-none active:opacity-[0.85] active:shadow-none disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none">
                    <form class="flex space-x-4">
                        <!-- Form items go here -->
                        <div class="relative flex p-2 bg-white border-2 shadow rounded-xl">
                            <span class="flex items-center justify-end w-auto p-2 text-gray-500">
                                <svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path>
                                </svg>
                            </span>
                            <input type="text" id="job_title" name="job_title" class="w-full p-2 text-sm border-0" placeholder="Search Jobs"/>
                        
                        
                            <div class="flex items-center w-auto mr-2 text-sm text-gray-500 justify-items-center">
                                <label class="p-1 mt-2" for="job_country">Location: </label>
                                <input type="text" id="job_country" name="job_country" class="w-full p-0 text-sm border-0" placeholder="Where?"/>
                            </div>
                        
                            <div class="flex-1">
                                <!-- Add more form fields as needed -->
                            </div>
                        
                            <div class="flex-1">
                                <button type="submit" class="flex p-2 text-xl text-green-500 bg-black hover:bg-gray-700 rounded-xl">
                                    <p class="text-sm font-semibold">Search</p>
                                    </button>
                            </div>
                        </div>
                    </form>
                </div>
                
            </div>
          </div>
          <!-- posts -->
            <div class="items-center w-full max-h-screen mb-5 mr-5 overflow-y-auto md:flex md:flex-col md-flex-1">
              {% for job in jobs %}
                <div class="items-center justify-center w-full max-h-screen">
                    <!-- posts -->
                    <div class="max-w-md p-2 mx-2 mb-4 shadow-md md:p-4 md:mx-6 hover:border-4 hover:border-amber-400">
                        <h2 class="text-xl font-semibold md:text-2xl"><a class="text-green-500 hover:text-black" href="{% url 'jobs:details' pk=job.id%}">{{job.job_title}}</a></h2>
                        <p class="text-sm leading-tight text-justify text-gray-800 truncate md:text-base">{{job.job_description}}</p>
                        <div class="flex justify-between mt-2">
                        <span>Posted On: {{job.job_posted_at_datetime_utc}}</span>
                        <span class="text-black">Date: <a class="text-green-500 hover:text-black" href="#">{{job.apply_options}}</a></span>
                        </div>
                    </div>
                </div>
              {% endfor %}
            </div>
        </div>  
        <div class="w-3/5 ml-5">
          <!-- post view -->
          <div class="right-0 flex-shrink-0 max-h-screen overflow-y-auto">
            {% include "jobs/partials/info.html" %}
          </div>
        </div>
      </div>
    </div>
    
</div>
       
             
    
{% endblock content %}

 

dev/src/templates/jobs/index.html
<!DOCTYPE html>
{% load static %}
{% load static tailwind_tags %}

<html>
<head>
	<title>Jobs+</title>
    {% tailwind_css %}
	<script>
	  window.dataLayer = window.dataLayer || [];
	  function gtag(){dataLayer.push(arguments);}
	  gtag('js', new Date());

	  gtag('config', 'UA-47692315-56');
	</script>

	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

	
	<link id="theme-style" rel="stylesheet" type="text/css" href="">
</head>

  <body class="h-screen">

    <!-- some things work some of the time dark:bg-black    <link rel="stylesheet" type="text/css" href="{% static '' %}">-->
    <div class="flex flex-col h-5/6">
      
        <div class="">
          <!-- Include the top bar and content wrapper -->
          {% include "jobs/partials/navbar.html" %}
          
          <div class="flex flex-col min-h-screen text-2xl font-bold ">
            <!-- Content -->
            {% block content %}
            {% endblock content %}
          </div>
        </div>
      
      

      <div class="mt-32">
        {% include "jobs/partials/footer.html" %}
      </div>
    </div>
    
    
  </body>

</html>

dev/src/templates/jobs/partials/footer.html
<!-- Section 1 -->

    <div class="max-w-screen-xl px-4 py-2 mx-auto space-y-5 overflow-hidden sm:px-6 lg:px-8">
        <nav class="flex flex-wrap justify-center mx-5 my-0">
            <div class="px-32 py-2 m-0">
                <a href="{% url 'jobs:about' %}" class="text-base leading-6 text-gray-500 hover:text-gray-900">
                    About
                </a>
            </div>
            <!--
            <div class="px-5 py-2">
                <a href="#" class="text-base leading-6 text-gray-500 hover:text-gray-900">
                    Team
                </a>
            </div>
            <div class="px-5 py-2">
                <a href="#" class="text-base leading-6 text-gray-500 hover:text-gray-900">
                    blog
                </a>
            </div>
            <div class="px-5 py-2">
                <a href="#" class="text-base leading-6 text-gray-500 hover:text-gray-900">
                    Pricing
                </a>
            </div>
            <div class="px-5 py-2">
                <a href="#" class="text-base leading-6 text-gray-500 hover:text-gray-900">
                    Contact
                </a>
            </div>
            <div class="px-5 py-2">
                <a href="#" class="text-base leading-6 text-gray-500 hover:text-gray-900">
                    Terms
                </a>
            </div>-->
        </nav>
        <div class="flex justify-center mt-3 space-x-6">
            <a href="#" class="text-gray-400 hover:text-gray-500">
                <span class="sr-only">Facebook</span>
                <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 24 24">
                    <path fill-rule="evenodd" d="M22 12c0-5.523-4.477-10-10-10S2 6.477 2 12c0 4.991 3.657 9.128 8.438 9.878v-6.987h-2.54V12h2.54V9.797c0-2.506 1.492-3.89 3.777-3.89 1.094 0 2.238.195 2.238.195v2.46h-1.26c-1.243 0-1.63.771-1.63 1.562V12h2.773l-.443 2.89h-2.33v6.988C18.343 21.128 22 16.991 22 12z" clip-rule="evenodd"></path>
                </svg>
            </a>
            <a href="#" class="text-gray-400 hover:text-gray-500">
                <span class="sr-only">Instagram</span>
                <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 24 24">
                    <path fill-rule="evenodd" d="M12.315 2c2.43 0 2.784.013 3.808.06 1.064.049 1.791.218 2.427.465a4.902 4.902 0 011.772 1.153 4.902 4.902 0 011.153 1.772c.247.636.416 1.363.465 2.427.048 1.067.06 1.407.06 4.123v.08c0 2.643-.012 2.987-.06 4.043-.049 1.064-.218 1.791-.465 2.427a4.902 4.902 0 01-1.153 1.772 4.902 4.902 0 01-1.772 1.153c-.636.247-1.363.416-2.427.465-1.067.048-1.407.06-4.123.06h-.08c-2.643 0-2.987-.012-4.043-.06-1.064-.049-1.791-.218-2.427-.465a4.902 4.902 0 01-1.772-1.153 4.902 4.902 0 01-1.153-1.772c-.247-.636-.416-1.363-.465-2.427-.047-1.024-.06-1.379-.06-3.808v-.63c0-2.43.013-2.784.06-3.808.049-1.064.218-1.791.465-2.427a4.902 4.902 0 011.153-1.772A4.902 4.902 0 015.45 2.525c.636-.247 1.363-.416 2.427-.465C8.901 2.013 9.256 2 11.685 2h.63zm-.081 1.802h-.468c-2.456 0-2.784.011-3.807.058-.975.045-1.504.207-1.857.344-.467.182-.8.398-1.15.748-.35.35-.566.683-.748 1.15-.137.353-.3.882-.344 1.857-.047 1.023-.058 1.351-.058 3.807v.468c0 2.456.011 2.784.058 3.807.045.975.207 1.504.344 1.857.182.466.399.8.748 1.15.35.35.683.566 1.15.748.353.137.882.3 1.857.344 1.054.048 1.37.058 4.041.058h.08c2.597 0 2.917-.01 3.96-.058.976-.045 1.505-.207 1.858-.344.466-.182.8-.398 1.15-.748.35-.35.566-.683.748-1.15.137-.353.3-.882.344-1.857.048-1.055.058-1.37.058-4.041v-.08c0-2.597-.01-2.917-.058-3.96-.045-.976-.207-1.505-.344-1.858a3.097 3.097 0 00-.748-1.15 3.098 3.098 0 00-1.15-.748c-.353-.137-.882-.3-1.857-.344-1.023-.047-1.351-.058-3.807-.058zM12 6.865a5.135 5.135 0 110 10.27 5.135 5.135 0 010-10.27zm0 1.802a3.333 3.333 0 100 6.666 3.333 3.333 0 000-6.666zm5.338-3.205a1.2 1.2 0 110 2.4 1.2 1.2 0 010-2.4z" clip-rule="evenodd"></path>
                </svg>
            </a>
            <a href="https://twitter.com/entry55802" class="text-gray-400 hover:text-gray-500">
                <span class="sr-only">Twitter</span>
                <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 24 24">
                    <path d="M8.29 20.251c7.547 0 11.675-6.253 11.675-11.675 0-.178 0-.355-.012-.53A8.348 8.348 0 0022 5.92a8.19 8.19 0 01-2.357.646 4.118 4.118 0 001.804-2.27 8.224 8.224 0 01-2.605.996 4.107 4.107 0 00-6.993 3.743 11.65 11.65 0 01-8.457-4.287 4.106 4.106 0 001.27 5.477A4.072 4.072 0 012.8 9.713v.052a4.105 4.105 0 003.292 4.022 4.095 4.095 0 01-1.853.07 4.108 4.108 0 003.834 2.85A8.233 8.233 0 012 18.407a11.616 11.616 0 006.29 1.84"></path>
                </svg>
            </a>
            <a href="https://www.tiktok.com/@crafman.jobs" class="text-gray-400 hover:text-gray-500">
                <span class="sr-only">TikTok</span>
                <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 24 24">
                    <path fill-rule="evenodd" d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10c5.51 0 10-4.48 10-10S17.51 2 12 2zm6.605 4.61a8.502 8.502 0 011.93 5.314c-.281-.054-3.101-.629-5.943-.271-.065-.141-.12-.293-.184-.445a25.416 25.416 0 00-.564-1.236c3.145-1.28 4.577-3.124 4.761-3.362zM12 3.475c2.17 0 4.154.813 5.662 2.148-.152.216-1.443 1.941-4.48 3.08-1.399-2.57-2.95-4.675-3.189-5A8.687 8.687 0 0112 3.475zm-3.633.803a53.896 53.896 0 013.167 4.935c-3.992 1.063-7.517 1.04-7.896 1.04a8.581 8.581 0 014.729-5.975zM3.453 12.01v-.26c.37.01 4.512.065 8.775-1.215.25.477.477.965.694 1.453-.109.033-.228.065-.336.098-4.404 1.42-6.747 5.303-6.942 5.629a8.522 8.522 0 01-2.19-5.705zM12 20.547a8.482 8.482 0 01-5.239-1.8c.152-.315 1.888-3.656 6.703-5.337.022-.01.033-.01.054-.022a35.318 35.318 0 011.823 6.475 8.4 8.4 0 01-3.341.684zm4.761-1.465c-.086-.52-.542-3.015-1.659-6.084 2.679-.423 5.022.271 5.314.369a8.468 8.468 0 01-3.655 5.715z" clip-rule="evenodd"></path>
                </svg>
            </a>
        </div>
        <p class="mt-8 text-base leading-6 text-center text-gray-400">
            © 2023 AllJobs, Inc. All rights reserved.
        </p>
    </div>

dev/src/templates/jobs/partials/navbar.html
<!-- top nav -->
<!-- Navbar -->
{% load static %}
<nav class="fixed top-0 left-0 right-0 flex flex-row justify-around w-full py-1 bg-green-500 shadow-md z-12 backdrop-blur-md">

    <!-- Logo Container -->
    <div class="flex items-center">
        <!-- Logo <button>
            <a class="text-yellow-500 " href="{% url 'jobs:home' %}">
                <h1 class="text-yellow-500 flex-nowrap">JobsPlus</h1>
            </a>
        </button>-->
        <a class="text-white cursor-pointer" href="{% url 'jobs:home' %}">
            <h1 class="text-5xl font-bold hover:text-yellow-400">JobsPlus</h1>
            <h3 class="text-2xl font-medium text-white>
                <img class="" src="{% static 'jobs/img/logo-color.png' %}" alt="JobsPlus logo">
            </h3>
        </a>
        
    </div>



    <!-- Icon Menu Section -->
    <div class="flex items-center space-x-5">
        <!-- Register -->
        <button>
            <a class="flex text-white transition-colors duration-300 cursor-pointer hover:text-blue-500" href="{% url 'jobs:about' %}">

                <svg class="fill-current h-5 w-5 mr-2 mt-0.5" xmlns="http://www.w3.org/2000/svg"
                    xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="24" height="24"
                    viewBox="0 0 24 24">
                    <path
                        d="M12 0L11.34 .03L15.15 3.84L16.5 2.5C19.75 4.07 22.09 7.24 22.45 11H23.95C23.44 4.84 18.29 0 12 0M12 4C10.07 4 8.5 5.57 8.5 7.5C8.5 9.43 10.07 11 12 11C13.93 11 15.5 9.43 15.5 7.5C15.5 5.57 13.93 4 12 4M12 6C12.83 6 13.5 6.67 13.5 7.5C13.5 8.33 12.83 9 12 9C11.17 9 10.5 8.33 10.5 7.5C10.5 6.67 11.17 6 12 6M.05 13C.56 19.16 5.71 24 12 24L12.66 23.97L8.85 20.16L7.5 21.5C4.25 19.94 1.91 16.76 1.55 13H.05M12 13C8.13 13 5 14.57 5 16.5V18H19V16.5C19 14.57 15.87 13 12 13M12 15C14.11 15 15.61 15.53 16.39 16H7.61C8.39 15.53 9.89 15 12 15Z" />
                </svg>

                About
            </a>
        </button>
        <!-- Login 
        <a class="flex font-semibold text-gray-600 transition-colors duration-300 cursor-pointer">

            <svg class="fill-current h-5 w-5 mr-2 mt-0.5" xmlns="http://www.w3.org/2000/svg"
                xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="24" height="24"
                viewBox="0 0 24 24">
                <path
                    d="M10,17V14H3V10H10V7L15,12L10,17M10,2H19A2,2 0 0,1 21,4V20A2,2 0 0,1 19,22H10A2,2 0 0,1 8,20V18H10V20H19V4H10V6H8V4A2,2 0 0,1 10,2Z" />
            </svg>

            Login
        </a>-->
    </div>
    
</nav>

dev/theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>